---
- name: Configure rsyslog
  hosts: all

  tasks:
  - name: Remove remote rsyslog entry
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^\*\.info @<remote name>'
      state: absent
      validate: /usr/sbin/rsyslogd -N1 -f %s
    notify:
      - Restart rsyslog

  handlers:
  - name: Restart rsyslog
    service:
      name: rsyslog
      state: restarted
